name: Deploy Backend
on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'Deploy analyze-log'
        run: |
          gcloud functions deploy analyze-log \
            --gen2 \
            --runtime=python311 \
            --region=us-central1 \
            --source=./backend \
            --entry-point=analyze_log \
            --trigger-http \
            --allow-unauthenticated
